refactor: logger
VladislavkiSelov/nodejs24_hw_-VLADISLAV_KISELOV- pull request #5
Opened 2024-02-10 19:57 UTC by VladislavkiSelov

HW4

2024-02-10 20:44 UTC, evhenious commented on main.js
> +process.on("beforeExit", () => {
Оцю штуку можна зробити в самому логгері, буде працювати так само (`process` глобально доступний, не тільки в точці входу в програму)

2024-02-10 20:46 UTC, evhenious commented on utils/logger.js
> +    if (!fileLogs.includes("logs")) {
можна не перевіряти чи є самі файли. Коли відкриваєш файлстрім на запис, він сам створить потрібний файл на диску якщо файла немає

2024-02-10 20:51 UTC, evhenious commented on utils/logger.js
> +  const date = moment(new Date()).format("YY.MM.DD");
уяви тонну логів з однаковою датою)) я б на твоєму місці ще додав час події ))

2024-02-10 20:54 UTC, evhenious commented on utils/logger.js
> +const writeStreamInfo = fs.createWriteStream(path.join(".", "logs", "info.log"), { encoding: "utf-8", highWaterMark: 1024 });
старі логи непогано зберігати. щоб наприклад, випадковий рестарт програми не перезатер всю зібану інфу. Для цього достатньо додати в опції стріма ключ `flags: 'a'`

2024-02-10 20:56 UTC, evhenious commented on utils/logger.js
> +      fs.mkdirSync(path.join(".", "logs"));
в тебе папка `logs` додається в `utils`. Краще всеж в project root

2024-02-10 20:58 UTC, evhenious commented on utils/logger.js
> +module.exports = { createLogger, writeStreamInfo, writeStreamError };
поверни будь ласка експорти як вони були. Файлстріми ці не потрібні нікому окрім логгера, тому й. експортувати їх не варто

2024-02-10 21:01 UTC, evhenious requested changes
Основне - поправ будь ласка імпорти як були, і перенеси закриття файлстрімов в логгер

Другорядне - записувати в логфайл дату і час подій, а не тільки дату

2024-02-11 06:50 UTC, VladislavkiSelov commented on utils/logger.js
> +      fs.mkdirSync(path.join(".", "logs"));
тут трохи не зрозумів, я перевіряю чи є папка logs в корні проекта і потім створюю її в корні проекта 
![photo_2024-02-11_08-49-23](https://github.com/VladislavkiSelov/nodejs24_hw_-VLADISLAV_KISELOV-/assets/111900758/2b7d6541-7156-4de8-953d-baca1c99880a)

2024-02-11 07:18 UTC, evhenious commented on utils/logger.js
> +      fs.mkdirSync(path.join(".", "logs"));
Так, все з цим ОК у тебе, перепрошую за false alarm

2024-02-11 07:19 UTC, evhenious approved these changes

2024-02-11 07:19 UTC, merged